#!/bin/bash
DOMAIN=${1:-magento2-dockerized.local}
VERSION=${2:-2.3.5-p1}

curl -s https://raw.githubusercontent.com/mlabate/docker-magento2/master/lib/template | bash -s - magento-2
bin/download $VERSION

echo "Your system password has been requested to add an entry to /etc/hosts..."
echo "127.0.0.1 ::1 $DOMAIN" | sudo tee -a /etc/hosts

bin/setup $DOMAIN
